update plugin
-add missing  import locale
-small correct skins
-gettext some titles
-fix two error
File
"/usr/lib/enigma2/python/Plugins/Extensions/SubsSupport/seekers/utilities.py",
line 308, in getFileSize
    if os.path.isfile(filepath):
  File
"/usr/lib/python2.7/genericpath.py", line 29, in
isfile
UnicodeEncodeError: 'ascii' codec can't encode characters in
position 5-11: ordinal not in range(128)

File "/usr/lib/enigma2/python/Plugins/Extensions/SubsSupport/utils.py",
line 17, in load
    with open(subpath, 'r') as f:
UnicodeEncodeError:
'ascii' codec can't encode characters in position 5-11: ordinal not in
range(128)